/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author LuisG
 */
public class PanelDatos extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatos
     */
    public PanelDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFuncion = new javax.swing.JLabel();
        txtFuncion = new javax.swing.JTextField();
        txtDerivada = new javax.swing.JTextField();
        lblDerivada = new javax.swing.JLabel();
        lblIntervalos = new javax.swing.JLabel();
        txtIntervaloA = new javax.swing.JTextField();
        txtIntervaloB = new javax.swing.JTextField();
        txtNumeroIteraciones = new javax.swing.JTextField();
        txtP0 = new javax.swing.JTextField();
        lblPo = new javax.swing.JLabel();
        lblNumeroIteraciones = new javax.swing.JLabel();
        lblRaiz = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        lblSegundaDerivada = new javax.swing.JLabel();
        txtSegundaDerivada = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Función"));
        setMaximumSize(new java.awt.Dimension(395, 150));
        setMinimumSize(new java.awt.Dimension(395, 150));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(395, 150));

        lblFuncion.setText("Función: f(x) =");

        txtFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncionActionPerformed(evt);
            }
        });

        txtDerivada.setEditable(false);

        lblDerivada.setText("Derivada: f ' (x) =");

        lblIntervalos.setText("Intervalos: [A,B] =");

        txtIntervaloA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntervaloAActionPerformed(evt);
            }
        });

        lblPo.setText("P0 =");

        lblNumeroIteraciones.setText("Numero de iteraciones:");

        lblRaiz.setText("Raiz =");

        txtResultado.setEditable(false);

        lblSegundaDerivada.setText("Derivada: f ' ' (x) =");

        txtSegundaDerivada.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDerivada)
                                    .addComponent(lblFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDerivada)
                                    .addComponent(txtFuncion)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIntervalos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIntervaloA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIntervaloB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblNumeroIteraciones)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumeroIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(txtP0))))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSegundaDerivada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSegundaDerivada)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDerivada)
                    .addComponent(txtDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSegundaDerivada)
                    .addComponent(txtSegundaDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblIntervalos))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIntervaloB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIntervaloA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPo)
                            .addComponent(txtP0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumeroIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumeroIteraciones))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRaiz)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncionActionPerformed
    }//GEN-LAST:event_txtFuncionActionPerformed

    private void txtIntervaloAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntervaloAActionPerformed
    }//GEN-LAST:event_txtIntervaloAActionPerformed

    public String darFuncion() {

        expresionMatematica = txtFuncion.getText();

        return expresionMatematica;

    }
    
    public double darIntervaloA() {

        try {

            a = Double.parseDouble(txtIntervaloA.getText());

        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(null, "Ponga un numero valido, por favor");

        }

        return a;

    }

    public double darIntervaloB() {

        try {

            b = Double.parseDouble(txtIntervaloB.getText());

        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(null, "Ponga un numero valido, por favor");

        }

        return b;

    }
    
    public double darP0() {

        try {

            p0 = Double.parseDouble(txtP0.getText());

        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(null, "Ponga un numero valido, por favor");

        }

        return p0;

    }

    public double darNumeroMaximoIteraciones() {

        try {

            precision = Double.parseDouble(txtNumeroIteraciones.getText());

        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(null, "Ponga un numero valido, por favor");

        }

        return precision;

    }

    public void mostrarRaiz(double raiz) {

        String texto = Double.toString(raiz);
        txtResultado.setText(texto);

    }
    
    public void mostrarDerivada(String derivada) {
        
        this.txtDerivada.setText(derivada);
        
    }
 
    public void mostrarSegundaDerivada(String sDerivada) {
       
        txtSegundaDerivada.setText(sDerivada);
        
    }

    private String expresionMatematica;
    private String expresionDerivada;
    private String expresionSegundoDerivada;

    private double a;
    private double b;
    private double precision;
    private double p0;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDerivada;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblIntervalos;
    private javax.swing.JLabel lblNumeroIteraciones;
    private javax.swing.JLabel lblPo;
    private javax.swing.JLabel lblRaiz;
    private javax.swing.JLabel lblSegundaDerivada;
    private javax.swing.JTextField txtDerivada;
    private javax.swing.JTextField txtFuncion;
    private javax.swing.JTextField txtIntervaloA;
    private javax.swing.JTextField txtIntervaloB;
    private javax.swing.JTextField txtNumeroIteraciones;
    private javax.swing.JTextField txtP0;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtSegundaDerivada;
    // End of variables declaration//GEN-END:variables
}
