/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author LuisG
 */
public class PanelDatos extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatos
     */
    public PanelDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFuncion = new javax.swing.JLabel();
        txtFuncion = new javax.swing.JTextField();
        lblIntervalos = new javax.swing.JLabel();
        txtIntervaloA = new javax.swing.JTextField();
        txtIntervaloB = new javax.swing.JTextField();
        txtNumeroIteraciones = new javax.swing.JTextField();
        lblNumeroIteraciones = new javax.swing.JLabel();
        lblRaiz = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Función"));
        setMaximumSize(new java.awt.Dimension(395, 150));
        setMinimumSize(new java.awt.Dimension(395, 150));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(395, 150));

        lblFuncion.setText("Función: f(x) =");

        txtFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncionActionPerformed(evt);
            }
        });

        lblIntervalos.setText("Intervalos: [A,B] =");

        txtIntervaloA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntervaloAActionPerformed(evt);
            }
        });

        lblNumeroIteraciones.setText("Numero de iteraciones:");

        lblRaiz.setText("Raiz =");

        txtResultado.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(txtFuncion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIntervalos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIntervaloA, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIntervaloB, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumeroIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroIteraciones)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncion)
                    .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIntervaloB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIntervaloA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntervalos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroIteraciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRaiz))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncionActionPerformed
    }//GEN-LAST:event_txtFuncionActionPerformed

    private void txtIntervaloAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntervaloAActionPerformed
    }//GEN-LAST:event_txtIntervaloAActionPerformed

    public String darFuncion() {

        expresionMatematica = txtFuncion.getText();

        return expresionMatematica;

    }
    
    public double darIntervaloA() {

        try {

            a = Double.parseDouble(txtIntervaloA.getText());

        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(null, "Ponga un numero valido, por favor");

        }

        return a;

    }

    public double darIntervaloB() {

        try {

            b = Double.parseDouble(txtIntervaloB.getText());

        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(null, "Ponga un numero valido, por favor");

        }

        return b;

    }
    
    public double darNumeroMaximoIteraciones() {

        try {

            precision = Double.parseDouble(txtNumeroIteraciones.getText());

        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(null, "Ponga un numero valido, por favor");

        }

        return precision;

    }

    public void mostrarRaiz(double raiz) {

        String texto = Double.toString(raiz);
        txtResultado.setText(texto);

    }
    
    private String expresionMatematica;

    private double a;
    private double b;
    private double precision;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblIntervalos;
    private javax.swing.JLabel lblNumeroIteraciones;
    private javax.swing.JLabel lblRaiz;
    private javax.swing.JTextField txtFuncion;
    private javax.swing.JTextField txtIntervaloA;
    private javax.swing.JTextField txtIntervaloB;
    private javax.swing.JTextField txtNumeroIteraciones;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
