/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author LuisG
 */
public class PanelIteraciones extends javax.swing.JPanel {

    /**
     * Creates new form PanelIteraciones
     */
    public PanelIteraciones() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScroll = new javax.swing.JScrollPane();
        txtIteraciones = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Iteraciones"));

        txtIteraciones.setEditable(false);
        txtIteraciones.setColumns(20);
        txtIteraciones.setRows(5);
        panelScroll.setViewportView(txtIteraciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarRaiz(double raizIteracion, int contador) {

        String texto = "X" + contador + " = " + Double.toString(raizIteracion) + "\n";
        txtIteraciones.setText(txtIteraciones.getText() + texto);

    }

    public void borrar() {

        txtIteraciones.setText("");

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane panelScroll;
    private javax.swing.JTextArea txtIteraciones;
    // End of variables declaration//GEN-END:variables

}
